### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by Albert-wa** [SenseRoboticsLab/CURL-MAP#1]
![Image](https://github.com/user-attachments/assets/7dca9d4f-526a-4472-9097-e7356a9f2b7f)
Hi author, I met a docker build problem that cannot cd to CURL_SLAM_ros. Is 'cd CURL-MAP' correct? or some other repo we used

**Comment by Albert-wa** [comment]
I think it might be 'CURL-MAP'. BTW, may we upsample a single pcd file rather than continuous slam, like the previous work CURL?

**Comment by sco09** [comment]
> I think it might be 'CURL-MAP'. BTW, may we upsample a single pcd file rather than continuous slam, like the previous work CURL?

Thank you for your interest in our work.

I've corrected the Dockerfile. This project is primarily designed for incremental mapping and odometry. While it can process a single scan, if you like, I am afraid it won't have a better result than CURL.

**Comment by patripfr** [comment]
The dockerfile is still broken, since the branch "ICRA24" does not exist anymore.

**Comment by sco09** [comment]
> The dockerfile is still broken, since the branch "ICRA24" does not exist anymore.

Thanks, I removed "git checkout ICRA24"

**Comment by patripfr** [comment]
I realized that even after successfully building the docker, there are a lot of broken things in the launch and yaml files, wrong file paths etc. Unfortunately the instructions in the readme are unusable like this :(

**Comment by sco09** [comment]
> I realized that even after successfully building the docker, there are a lot of broken things in the launch and yaml files, wrong file paths etc. Unfortunately the instructions in the readme are unusable like this :(

Sorry for the inconvenience. I am building this image and will test it and fix any bugs that may arise.

**Comment by sco09** [comment]
> I realized that even after successfully building the docker, there are a lot of broken things in the launch and yaml files, wrong file paths etc. Unfortunately the instructions in the readme are unusable like this :(

Hi there, it should work now. Inside your container run `cd /home/user/catkin_ws/src`, `rm -rf CURL-MAP`, `git clone https://github.com/SenseRoboticsLab/CURL-MAP.git`

Then the instructions in the readme should work.

**Comment by patripfr** [comment]
It works now :) Thanks a lot for fixing and open-sourcing the code!

**Comment by sco09** [comment]
> It works now :) Thanks a lot for fixing and open-sourcing the code!

You're welcome! Let me know if any other problems. Thanks!
